name: File Change Tracker

on:
  push:
    branches:
      - main

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

    - name: Run Python script to print changed files
      run: |
        python -c "
import subprocess
changed_files = subprocess.check_output(['git', 'diff', '--name-only', 'HEAD~1']).decode('utf-8').splitlines()
print('Changed files:')
for file in changed_files:
    print(file)
        "