name: File Change Tracker

on:
  push:
    branches:
      - main

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script to print changed files
      run: |
        python -c "
import subprocess
changed_files = subprocess.check_output(['git', 'diff', '--name-only', 'HEAD~1']).decode('utf-8').splitlines()
print('Changed files:')
for file in changed_files:
    print(file)
        "
